# Generated by Django 4.2.3 on 2023-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
